// ─── 8 Main Roles shown on home page (DO NOT CHANGE) ─────────────────────────
export const ROLES = {
  frontend:  { label: 'Frontend Dev',      icon: '⚡', accent: 'var(--accent-a)', dim: 'var(--accent-a-dim)' },
  backend:   { label: 'Backend Dev',       icon: '⚙',  accent: 'var(--accent-b)', dim: 'var(--accent-b-dim)' },
  aiml:      { label: 'AI/ML Engineer',    icon: '◈',  accent: 'var(--accent-c)', dim: 'var(--accent-c-dim)' },
  fullstack: { label: 'Full Stack Dev',    icon: '◎',  accent: 'var(--accent-a)', dim: 'var(--accent-a-dim)' },
  devops:    { label: 'DevOps Engineer',   icon: '🔧', accent: 'var(--accent-b)', dim: 'var(--accent-b-dim)' },
  mobile:    { label: 'Mobile Dev',        icon: '📱', accent: 'var(--accent-c)', dim: 'var(--accent-c-dim)' },
  security:  { label: 'Security Engineer', icon: '🔐', accent: 'var(--accent-a)', dim: 'var(--accent-a-dim)' },
  data:      { label: 'Data Engineer',     icon: '📊', accent: 'var(--accent-b)', dim: 'var(--accent-b-dim)' },
};

// ─── Extended Roles (search-only, not on home grid) ───────────────────────────
export const EXTENDED_ROLES = {
  // Software Development & Engineering
  software_architect:   { label: 'Software Architect',        icon: '🏛️', cat: 'Software Development' },
  qa_engineer:          { label: 'QA / Automation Engineer',  icon: '🧪', cat: 'Software Development' },
  // Data Science & AI
  data_scientist:       { label: 'Data Scientist',            icon: '🔬', cat: 'Data Science & AI' },
  nlp_engineer:         { label: 'NLP Engineer',              icon: '💬', cat: 'Data Science & AI' },
  computer_vision:      { label: 'Computer Vision Engineer',  icon: '👁️',  cat: 'Data Science & AI' },
  ai_ethics:            { label: 'AI Ethics Specialist',      icon: '⚖️',  cat: 'Data Science & AI' },
  // Cloud & Infrastructure
  cloud_engineer:       { label: 'Cloud Engineer',            icon: '☁️',  cat: 'Cloud & Infrastructure' },
  sre:                  { label: 'Site Reliability Engineer',  icon: '🛡️',  cat: 'Cloud & Infrastructure' },
  sysadmin:             { label: 'Systems Administrator',     icon: '🖥️',  cat: 'Cloud & Infrastructure' },
  network_architect:    { label: 'Network Architect',         icon: '🌐', cat: 'Cloud & Infrastructure' },
  // Cybersecurity
  security_analyst:     { label: 'Cybersecurity Analyst',     icon: '🔍', cat: 'Cybersecurity' },
  pen_tester:           { label: 'Ethical Hacker / Pen Tester', icon: '🕵️', cat: 'Cybersecurity' },
  security_architect:   { label: 'Security Architect',        icon: '🏰', cat: 'Cybersecurity' },
  infosec_manager:      { label: 'Info Security Manager',     icon: '📋', cat: 'Cybersecurity' },
  digital_forensics:    { label: 'Digital Forensics Specialist', icon: '🔎', cat: 'Cybersecurity' },
  // Specialized Roles
  blockchain_dev:       { label: 'Blockchain Developer',      icon: '⛓️',  cat: 'Specialized' },
  game_dev:             { label: 'Game Developer',            icon: '🎮', cat: 'Specialized' },
  embedded_engineer:    { label: 'Embedded Systems Engineer', icon: '🔌', cat: 'Specialized' },
  iot_engineer:         { label: 'IoT Engineer',              icon: '📡', cat: 'Specialized' },
  ui_ux_designer:       { label: 'UI/UX Designer (Technical)',icon: '🎨', cat: 'Specialized' },
  ar_vr_dev:            { label: 'AR/VR Developer',           icon: '🥽', cat: 'Specialized' },
  dba:                  { label: 'Database Administrator',    icon: '🗃️',  cat: 'Specialized' },
};

// ─── All roles merged for search ─────────────────────────────────────────────
export const ALL_ROLES = { ...ROLES, ...EXTENDED_ROLES };

export const QUESTIONS = {
  // ── 8 MAIN ROLES ─────────────────────────────────────────────────────────
  frontend: [
    { q: "Explain the difference between var, let, and const in JavaScript.", cat: "JavaScript", diff: "Easy" },
    { q: "What is the Virtual DOM and how does React use it to improve performance?", cat: "React", diff: "Medium" },
    { q: "How does CSS Flexbox differ from CSS Grid? When would you use each?", cat: "CSS", diff: "Easy" },
    { q: "Explain closures in JavaScript with a real-world example.", cat: "JavaScript", diff: "Medium" },
    { q: "How would you optimize the performance of a slow React application?", cat: "Performance", diff: "Hard" },
    { q: "What is event delegation and why is it useful?", cat: "JavaScript", diff: "Medium" },
    { q: "What are React hooks? Explain useState and useEffect.", cat: "React", diff: "Medium" },
    { q: "How does the browser render a webpage (critical rendering path)?", cat: "Performance", diff: "Hard" },
    { q: "What is TypeScript and why would you choose it over plain JavaScript?", cat: "TypeScript", diff: "Easy" },
    { q: "What is code splitting and how do you implement it in React?", cat: "Performance", diff: "Hard" },
    { q: "How does async/await differ from Promises in JavaScript?", cat: "JavaScript", diff: "Medium" },
    { q: "Explain the concept of memoization and when to use React.memo.", cat: "React", diff: "Medium" },
    { q: "What are Web Workers and when would you use them?", cat: "Performance", diff: "Hard" },
    { q: "What is the difference between localStorage, sessionStorage, and cookies?", cat: "Browser APIs", diff: "Easy" },
    { q: "Explain the concept of a service worker and Progressive Web Apps.", cat: "PWA", diff: "Hard" },
    { q: "How would you implement infinite scroll in a React application?", cat: "React", diff: "Medium" },
    { q: "Explain debouncing and throttling with examples.", cat: "JavaScript", diff: "Medium" },
    { q: "What are the key principles of accessible web design (WCAG)?", cat: "Accessibility", diff: "Medium" },
    { q: "How does React's reconciliation algorithm work?", cat: "React", diff: "Hard" },
    { q: "Explain CORS and how to handle it in a front-end application.", cat: "Networking", diff: "Medium" },
    { q: "What is CSS specificity and how is it calculated?", cat: "CSS", diff: "Medium" },
    { q: "Explain the difference between == and === in JavaScript.", cat: "JavaScript", diff: "Easy" },
    { q: "How do you handle cross-browser compatibility issues?", cat: "CSS", diff: "Easy" },
    { q: "What is the purpose of a bundler like Webpack or Vite?", cat: "Tooling", diff: "Easy" },
    { q: "What is the purpose of a CSS preprocessor like SASS/SCSS?", cat: "CSS", diff: "Easy" },
  ],
  backend: [
    { q: "What is the difference between REST and GraphQL APIs?", cat: "API Design", diff: "Medium" },
    { q: "Explain database indexing and when should you use it.", cat: "Database", diff: "Medium" },
    { q: "What are microservices and what are their key benefits and drawbacks?", cat: "Architecture", diff: "Hard" },
    { q: "How does JWT authentication work end-to-end?", cat: "Security", diff: "Medium" },
    { q: "Explain the CAP theorem and its implications for distributed systems.", cat: "Distributed Systems", diff: "Hard" },
    { q: "What is connection pooling and why is it important?", cat: "Database", diff: "Medium" },
    { q: "How would you design a rate limiting system for an API?", cat: "System Design", diff: "Hard" },
    { q: "What are database transactions and ACID properties?", cat: "Database", diff: "Medium" },
    { q: "What is the N+1 query problem and how do you solve it?", cat: "Database", diff: "Medium" },
    { q: "How does message queuing work? (e.g., RabbitMQ, Kafka)", cat: "Architecture", diff: "Hard" },
    { q: "What is caching? Explain Redis and when to use it.", cat: "Performance", diff: "Medium" },
    { q: "How would you implement pagination in a REST API?", cat: "API Design", diff: "Easy" },
    { q: "What are webhooks and how do they differ from polling?", cat: "API Design", diff: "Medium" },
    { q: "How do you handle database migrations safely in production?", cat: "Database", diff: "Hard" },
    { q: "Explain OAuth 2.0 and when you'd use it.", cat: "Security", diff: "Medium" },
    { q: "What is a reverse proxy and why would you use Nginx?", cat: "Infrastructure", diff: "Medium" },
    { q: "Explain the concept of eventual consistency.", cat: "Distributed Systems", diff: "Hard" },
    { q: "How would you design a URL shortener at scale?", cat: "System Design", diff: "Hard" },
    { q: "How does gRPC differ from REST?", cat: "API Design", diff: "Medium" },
    { q: "Explain the concept of idempotency in API design.", cat: "API Design", diff: "Medium" },
    { q: "What is the difference between SQL and NoSQL databases?", cat: "Database", diff: "Easy" },
    { q: "Explain the event-driven architecture pattern.", cat: "Architecture", diff: "Hard" },
    { q: "What is the difference between horizontal and vertical scaling?", cat: "Infrastructure", diff: "Easy" },
    { q: "What are environment variables and why are they important for security?", cat: "Security", diff: "Easy" },
    { q: "Explain the difference between synchronous and asynchronous processing.", cat: "Architecture", diff: "Easy" },
  ],
  aiml: [
    { q: "Explain the difference between supervised and unsupervised learning.", cat: "Fundamentals", diff: "Easy" },
    { q: "What is overfitting, how do you detect it, and how do you prevent it?", cat: "Model Training", diff: "Medium" },
    { q: "Explain the transformer architecture and why it revolutionized NLP.", cat: "Deep Learning", diff: "Hard" },
    { q: "How does gradient descent work and what are its main variants?", cat: "Optimization", diff: "Medium" },
    { q: "What is the difference between precision, recall, and F1 score?", cat: "Metrics", diff: "Medium" },
    { q: "Explain how a convolutional neural network (CNN) works.", cat: "Deep Learning", diff: "Hard" },
    { q: "What is transfer learning and when would you use it?", cat: "Model Training", diff: "Medium" },
    { q: "Explain the bias-variance tradeoff.", cat: "Fundamentals", diff: "Medium" },
    { q: "How does the attention mechanism work in transformers?", cat: "Deep Learning", diff: "Hard" },
    { q: "What is RAG (Retrieval-Augmented Generation) and why is it useful?", cat: "LLMs", diff: "Medium" },
    { q: "Explain k-means clustering and its limitations.", cat: "Unsupervised", diff: "Easy" },
    { q: "What is a confusion matrix and how do you interpret it?", cat: "Metrics", diff: "Easy" },
    { q: "How does reinforcement learning differ from supervised learning?", cat: "Fundamentals", diff: "Medium" },
    { q: "Explain the concept of word embeddings (Word2Vec, GloVe).", cat: "NLP", diff: "Medium" },
    { q: "What is A/B testing and how is it used to evaluate ML models?", cat: "Evaluation", diff: "Easy" },
    { q: "Explain the concept of regularization (L1 vs L2).", cat: "Model Training", diff: "Medium" },
    { q: "What is fine-tuning a large language model?", cat: "LLMs", diff: "Medium" },
    { q: "How would you handle imbalanced datasets?", cat: "Data", diff: "Medium" },
    { q: "Explain principal component analysis (PCA).", cat: "Dimensionality", diff: "Hard" },
    { q: "How do you evaluate and reduce hallucinations in LLMs?", cat: "LLMs", diff: "Hard" },
    { q: "Explain vector databases and their role in AI systems.", cat: "Infrastructure", diff: "Medium" },
    { q: "What is prompt engineering and what are some effective techniques?", cat: "LLMs", diff: "Easy" },
    { q: "How does RLHF (Reinforcement Learning from Human Feedback) work?", cat: "LLMs", diff: "Hard" },
    { q: "What is the difference between batch normalization and layer normalization?", cat: "Deep Learning", diff: "Hard" },
    { q: "What is the difference between a model's accuracy and its robustness?", cat: "Evaluation", diff: "Medium" },
  ],
  fullstack: [
    { q: "Explain the MVC architecture pattern with an example.", cat: "Architecture", diff: "Easy" },
    { q: "How does HTTP/2 differ from HTTP/1.1 in terms of performance?", cat: "Networking", diff: "Medium" },
    { q: "What is CI/CD, and how does it improve the development workflow?", cat: "DevOps", diff: "Medium" },
    { q: "Design a scalable URL shortener system.", cat: "System Design", diff: "Hard" },
    { q: "How would you implement secure authentication in a full-stack application?", cat: "Security", diff: "Medium" },
    { q: "What is server-side rendering (SSR) vs. client-side rendering (CSR)?", cat: "Architecture", diff: "Medium" },
    { q: "Explain the BFF (Backend For Frontend) pattern.", cat: "Architecture", diff: "Hard" },
    { q: "How do you manage state in a large React application?", cat: "Frontend", diff: "Medium" },
    { q: "What is Docker and how does containerization help development?", cat: "DevOps", diff: "Easy" },
    { q: "How would you implement real-time features like notifications?", cat: "Backend", diff: "Hard" },
    { q: "What is GraphQL and when is it preferable to REST?", cat: "API Design", diff: "Medium" },
    { q: "Explain the concept of optimistic UI updates.", cat: "Frontend", diff: "Medium" },
    { q: "How do you approach database schema design for a social media app?", cat: "Database", diff: "Hard" },
    { q: "What is the difference between cookies and JWT for session management?", cat: "Security", diff: "Medium" },
    { q: "How would you implement file upload functionality securely?", cat: "Backend", diff: "Medium" },
    { q: "Explain micro-frontends and when you'd use them.", cat: "Architecture", diff: "Hard" },
    { q: "How do you monitor and debug a full-stack application in production?", cat: "DevOps", diff: "Medium" },
    { q: "How do you design APIs to be backward compatible?", cat: "API Design", diff: "Medium" },
    { q: "What is the role of a CDN in a full-stack application?", cat: "Infrastructure", diff: "Easy" },
    { q: "How would you handle time zones in a global application?", cat: "Backend", diff: "Medium" },
    { q: "Explain feature flags and how they enable safe deployments.", cat: "DevOps", diff: "Medium" },
    { q: "How do you approach testing a full-stack application? (unit, integration, e2e)", cat: "Testing", diff: "Medium" },
    { q: "Explain the concept of a monorepo and its advantages.", cat: "Architecture", diff: "Medium" },
    { q: "How do you handle environment configuration across dev/staging/prod?", cat: "DevOps", diff: "Easy" },
    { q: "What is edge computing and how does it differ from traditional cloud?", cat: "Infrastructure", diff: "Hard" },
  ],
  devops: [
    { q: "Explain the difference between Continuous Integration and Continuous Delivery.", cat: "CI/CD", diff: "Easy" },
    { q: "What is Infrastructure as Code? Compare Terraform and Ansible.", cat: "IaC", diff: "Medium" },
    { q: "How does Kubernetes orchestrate containers?", cat: "Kubernetes", diff: "Hard" },
    { q: "Explain blue-green deployments and canary releases.", cat: "Deployment", diff: "Medium" },
    { q: "What is a Kubernetes pod, deployment, and service?", cat: "Kubernetes", diff: "Medium" },
    { q: "How would you set up monitoring and alerting for a production system?", cat: "Observability", diff: "Medium" },
    { q: "What is GitOps and how does it differ from traditional CI/CD?", cat: "CI/CD", diff: "Hard" },
    { q: "Explain the concept of immutable infrastructure.", cat: "Infrastructure", diff: "Medium" },
    { q: "How do you manage secrets securely in a cloud environment?", cat: "Security", diff: "Medium" },
    { q: "What is the difference between horizontal and vertical pod autoscaling?", cat: "Kubernetes", diff: "Hard" },
    { q: "Explain the concept of a service mesh (e.g., Istio).", cat: "Kubernetes", diff: "Hard" },
    { q: "What is observability? Explain logs, metrics, and traces.", cat: "Observability", diff: "Medium" },
    { q: "How do you implement zero-downtime deployments?", cat: "Deployment", diff: "Hard" },
    { q: "What are Helm charts and how do they simplify Kubernetes deployments?", cat: "Kubernetes", diff: "Medium" },
    { q: "Explain the concept of chaos engineering and why it matters.", cat: "Reliability", diff: "Hard" },
  ],
  mobile: [
    { q: "What is the difference between React Native and Flutter?", cat: "Frameworks", diff: "Easy" },
    { q: "Explain the React Native bridge and its performance implications.", cat: "Architecture", diff: "Hard" },
    { q: "How do you handle offline support in a mobile application?", cat: "Architecture", diff: "Medium" },
    { q: "What are the key differences between iOS and Android development?", cat: "Platforms", diff: "Easy" },
    { q: "How do you optimize app startup time in React Native?", cat: "Performance", diff: "Hard" },
    { q: "Explain push notifications and how they work on iOS vs Android.", cat: "Features", diff: "Medium" },
    { q: "What is Expo and when would you choose it over bare React Native?", cat: "Tooling", diff: "Easy" },
    { q: "How do you handle deep linking in a mobile application?", cat: "Navigation", diff: "Medium" },
    { q: "What are the app store guidelines you need to follow for submission?", cat: "Deployment", diff: "Easy" },
    { q: "How would you implement biometric authentication in a mobile app?", cat: "Security", diff: "Medium" },
    { q: "Explain how state management works in Flutter.", cat: "Frameworks", diff: "Medium" },
    { q: "How do you test mobile applications effectively?", cat: "Testing", diff: "Medium" },
    { q: "What are native modules in React Native and when would you use them?", cat: "Architecture", diff: "Hard" },
    { q: "Explain the concept of code push and over-the-air updates.", cat: "Deployment", diff: "Medium" },
    { q: "How do you handle device permissions in mobile development?", cat: "Features", diff: "Easy" },
  ],
  security: [
    { q: "Explain the OWASP Top 10 security vulnerabilities.", cat: "Fundamentals", diff: "Medium" },
    { q: "What is SQL injection and how do you prevent it?", cat: "Vulnerabilities", diff: "Easy" },
    { q: "Explain XSS and CSRF attacks and their mitigations.", cat: "Vulnerabilities", diff: "Medium" },
    { q: "How does TLS/SSL work? Explain the handshake process.", cat: "Cryptography", diff: "Hard" },
    { q: "What is the principle of least privilege?", cat: "Fundamentals", diff: "Easy" },
    { q: "Explain penetration testing and its methodology.", cat: "Testing", diff: "Hard" },
    { q: "How do you implement secure password storage?", cat: "Authentication", diff: "Medium" },
    { q: "What is a zero-trust security model?", cat: "Architecture", diff: "Medium" },
    { q: "Explain symmetric vs asymmetric encryption with use cases.", cat: "Cryptography", diff: "Medium" },
    { q: "How would you conduct a security audit of an existing application?", cat: "Testing", diff: "Hard" },
    { q: "What is a man-in-the-middle attack and how is it prevented?", cat: "Vulnerabilities", diff: "Medium" },
    { q: "Explain the concept of defense in depth.", cat: "Architecture", diff: "Medium" },
    { q: "What is a security information and event management (SIEM) system?", cat: "Monitoring", diff: "Hard" },
    { q: "How does certificate pinning work and when should you use it?", cat: "Cryptography", diff: "Hard" },
    { q: "What is the difference between authentication and authorization?", cat: "Fundamentals", diff: "Easy" },
  ],
  data: [
    { q: "Explain the difference between ETL and ELT pipelines.", cat: "Pipelines", diff: "Easy" },
    { q: "What is Apache Spark and when would you use it over a traditional database?", cat: "Processing", diff: "Medium" },
    { q: "How do you design a data warehouse schema? (star vs snowflake)", cat: "Modeling", diff: "Medium" },
    { q: "What is stream processing and how does Kafka enable it?", cat: "Streaming", diff: "Hard" },
    { q: "Explain the concept of data lineage and why it matters.", cat: "Governance", diff: "Medium" },
    { q: "How do you handle data quality issues in a pipeline?", cat: "Quality", diff: "Medium" },
    { q: "What is a data lake vs a data warehouse?", cat: "Architecture", diff: "Easy" },
    { q: "Explain partitioning and bucketing in distributed systems.", cat: "Performance", diff: "Hard" },
    { q: "How do you approach slowly changing dimensions (SCD) in data modeling?", cat: "Modeling", diff: "Hard" },
    { q: "What is dbt and how does it fit into the modern data stack?", cat: "Tooling", diff: "Medium" },
    { q: "Explain the concept of a medallion architecture (Bronze/Silver/Gold).", cat: "Architecture", diff: "Medium" },
    { q: "How do you handle late-arriving data in stream processing?", cat: "Streaming", diff: "Hard" },
    { q: "What is Apache Airflow and how do you design DAGs?", cat: "Orchestration", diff: "Medium" },
    { q: "Explain GDPR compliance requirements for data engineering.", cat: "Governance", diff: "Medium" },
    { q: "What is the difference between OLAP and OLTP systems?", cat: "Architecture", diff: "Easy" },
  ],

  // ── EXTENDED ROLES ────────────────────────────────────────────────────────
  software_architect: [
    { q: "Explain the difference between monolithic and microservices architectures and when to choose each.", cat: "Architecture", diff: "Medium" },
    { q: "What are the SOLID principles? Give a real-world example of each.", cat: "Design Principles", diff: "Medium" },
    { q: "How do you design a system that handles 1 million concurrent users?", cat: "System Design", diff: "Hard" },
    { q: "Explain the CAP theorem and how it influences architectural decisions.", cat: "Distributed Systems", diff: "Hard" },
    { q: "What design patterns have you used most frequently and why?", cat: "Design Patterns", diff: "Medium" },
    { q: "How do you approach technical debt? When is it acceptable?", cat: "Engineering Practices", diff: "Medium" },
    { q: "Explain event sourcing and CQRS. When would you use them together?", cat: "Architecture", diff: "Hard" },
    { q: "How do you ensure a system remains maintainable as it scales?", cat: "Engineering Practices", diff: "Medium" },
    { q: "What is domain-driven design (DDD) and how does it improve architecture?", cat: "Architecture", diff: "Hard" },
    { q: "How do you make build-vs-buy decisions for software components?", cat: "Engineering Practices", diff: "Medium" },
    { q: "Explain the concept of a strangler fig pattern for legacy migration.", cat: "Architecture", diff: "Hard" },
    { q: "How do you document architectural decisions? What is an ADR?", cat: "Documentation", diff: "Easy" },
    { q: "What is Conway's Law and how does it affect software architecture?", cat: "Engineering Practices", diff: "Medium" },
    { q: "Explain the twelve-factor app methodology.", cat: "Engineering Practices", diff: "Medium" },
    { q: "How do you evaluate and select a technology stack for a new project?", cat: "Engineering Practices", diff: "Medium" },
  ],
  qa_engineer: [
    { q: "Explain the difference between unit, integration, and end-to-end testing.", cat: "Testing Types", diff: "Easy" },
    { q: "What is the test pyramid and why does it matter?", cat: "Strategy", diff: "Easy" },
    { q: "How do you design a test automation framework from scratch?", cat: "Automation", diff: "Hard" },
    { q: "Explain the difference between black-box and white-box testing.", cat: "Testing Types", diff: "Easy" },
    { q: "What is BDD (Behavior-Driven Development) and how do you implement it?", cat: "Methodology", diff: "Medium" },
    { q: "How do you handle flaky tests in a CI/CD pipeline?", cat: "Automation", diff: "Medium" },
    { q: "What is test coverage and how do you measure it effectively?", cat: "Metrics", diff: "Easy" },
    { q: "Explain performance testing. What tools and metrics do you use?", cat: "Performance Testing", diff: "Medium" },
    { q: "How do you write effective bug reports?", cat: "Process", diff: "Easy" },
    { q: "What is contract testing and how does Pact work?", cat: "Automation", diff: "Hard" },
    { q: "How do you test APIs effectively?", cat: "API Testing", diff: "Medium" },
    { q: "Explain shift-left testing and its benefits.", cat: "Strategy", diff: "Medium" },
    { q: "What is mutation testing and when would you use it?", cat: "Advanced", diff: "Hard" },
    { q: "How do you prioritize which tests to automate first?", cat: "Strategy", diff: "Medium" },
    { q: "What are the challenges of testing microservices?", cat: "Advanced", diff: "Hard" },
  ],
  data_scientist: [
    { q: "Walk me through your typical data science project workflow.", cat: "Process", diff: "Easy" },
    { q: "Explain the difference between correlation and causation with an example.", cat: "Statistics", diff: "Easy" },
    { q: "How do you handle missing data in a dataset?", cat: "Data Preparation", diff: "Easy" },
    { q: "What is cross-validation and why is it important?", cat: "Model Evaluation", diff: "Medium" },
    { q: "Explain the difference between bagging and boosting.", cat: "Ensemble Methods", diff: "Medium" },
    { q: "How do you choose between different machine learning algorithms?", cat: "Model Selection", diff: "Medium" },
    { q: "What is the curse of dimensionality?", cat: "Fundamentals", diff: "Medium" },
    { q: "Explain hypothesis testing and p-values in plain language.", cat: "Statistics", diff: "Medium" },
    { q: "How do you communicate model results to non-technical stakeholders?", cat: "Communication", diff: "Easy" },
    { q: "What is SHAP and how does it help with model explainability?", cat: "Interpretability", diff: "Hard" },
    { q: "Explain the difference between parametric and non-parametric models.", cat: "Fundamentals", diff: "Medium" },
    { q: "How do you detect and handle outliers in a dataset?", cat: "Data Preparation", diff: "Medium" },
    { q: "What is feature engineering and why is it important?", cat: "Data Preparation", diff: "Medium" },
    { q: "Explain ROC-AUC and when it is preferred over accuracy.", cat: "Model Evaluation", diff: "Medium" },
    { q: "How would you build a recommendation system?", cat: "Applied ML", diff: "Hard" },
  ],
  nlp_engineer: [
    { q: "Explain tokenization and the challenges it poses for different languages.", cat: "Fundamentals", diff: "Easy" },
    { q: "What is the difference between stemming and lemmatization?", cat: "Text Processing", diff: "Easy" },
    { q: "Explain the BERT model architecture and what makes it powerful.", cat: "Transformers", diff: "Hard" },
    { q: "What is named entity recognition (NER) and how is it implemented?", cat: "NLP Tasks", diff: "Medium" },
    { q: "Explain how sentiment analysis works end-to-end.", cat: "NLP Tasks", diff: "Medium" },
    { q: "What are the challenges of building multilingual NLP systems?", cat: "Advanced", diff: "Hard" },
    { q: "How do you evaluate the quality of text generation models?", cat: "Evaluation", diff: "Medium" },
    { q: "Explain attention mechanisms in the context of machine translation.", cat: "Transformers", diff: "Hard" },
    { q: "What is the difference between extractive and abstractive summarization?", cat: "NLP Tasks", diff: "Medium" },
    { q: "How do you handle out-of-vocabulary words in NLP models?", cat: "Text Processing", diff: "Medium" },
    { q: "Explain Byte Pair Encoding (BPE) and subword tokenization.", cat: "Text Processing", diff: "Hard" },
    { q: "What is semantic search and how does it differ from keyword search?", cat: "Applications", diff: "Medium" },
    { q: "How would you build a question-answering system?", cat: "Applications", diff: "Hard" },
    { q: "What is TF-IDF and when would you still use it over neural approaches?", cat: "Text Processing", diff: "Easy" },
    { q: "Explain the challenges of detecting bias in NLP models.", cat: "Ethics", diff: "Hard" },
  ],
  computer_vision: [
    { q: "Explain how convolutional neural networks process images.", cat: "CNNs", diff: "Medium" },
    { q: "What is the difference between object detection and image segmentation?", cat: "Tasks", diff: "Easy" },
    { q: "Explain the YOLO architecture and why it's efficient.", cat: "Object Detection", diff: "Hard" },
    { q: "What data augmentation techniques do you use for computer vision?", cat: "Data", diff: "Easy" },
    { q: "How does transfer learning apply to computer vision tasks?", cat: "Transfer Learning", diff: "Medium" },
    { q: "What is the difference between semantic and instance segmentation?", cat: "Segmentation", diff: "Medium" },
    { q: "Explain the concept of feature pyramids in object detection.", cat: "Object Detection", diff: "Hard" },
    { q: "How do you handle class imbalance in image classification?", cat: "Data", diff: "Medium" },
    { q: "What is optical flow and how is it used in video analysis?", cat: "Video", diff: "Hard" },
    { q: "Explain the role of attention mechanisms in Vision Transformers (ViT).", cat: "Transformers", diff: "Hard" },
    { q: "How would you deploy a computer vision model to edge devices?", cat: "Deployment", diff: "Hard" },
    { q: "What is GAN (Generative Adversarial Network) and how does it work?", cat: "Generative Models", diff: "Hard" },
    { q: "How do you evaluate object detection model performance?", cat: "Evaluation", diff: "Medium" },
    { q: "What is image preprocessing and why is normalization important?", cat: "Data", diff: "Easy" },
    { q: "Explain the architecture of ResNet and the problem it solves.", cat: "CNNs", diff: "Hard" },
  ],
  ai_ethics: [
    { q: "What is algorithmic bias and how does it manifest in real-world AI systems?", cat: "Bias & Fairness", diff: "Medium" },
    { q: "Explain the concept of fairness in machine learning. What are the different definitions?", cat: "Bias & Fairness", diff: "Hard" },
    { q: "What is model explainability and why is it important for ethical AI?", cat: "Transparency", diff: "Medium" },
    { q: "How do you audit an AI system for potential ethical issues?", cat: "Governance", diff: "Hard" },
    { q: "What are the key privacy considerations when collecting data for ML?", cat: "Privacy", diff: "Medium" },
    { q: "Explain differential privacy and its applications in AI.", cat: "Privacy", diff: "Hard" },
    { q: "What is the EU AI Act and what does it mean for AI development?", cat: "Regulation", diff: "Medium" },
    { q: "How would you approach building an AI ethics review process?", cat: "Governance", diff: "Hard" },
    { q: "What is the difference between explainability and interpretability?", cat: "Transparency", diff: "Medium" },
    { q: "Explain the ethical implications of facial recognition technology.", cat: "Applications", diff: "Medium" },
    { q: "How do you handle the tension between model accuracy and fairness?", cat: "Bias & Fairness", diff: "Hard" },
    { q: "What is responsible AI and what are its core principles?", cat: "Frameworks", diff: "Easy" },
    { q: "How should organizations govern the deployment of generative AI?", cat: "Governance", diff: "Hard" },
    { q: "What are the risks of automation bias in AI-assisted decision making?", cat: "Human Factors", diff: "Medium" },
    { q: "Explain how to create model cards and datasheets for transparency.", cat: "Documentation", diff: "Medium" },
  ],
  cloud_engineer: [
    { q: "Compare AWS, Azure, and GCP. What are the key strengths of each?", cat: "Cloud Platforms", diff: "Medium" },
    { q: "Explain the difference between IaaS, PaaS, and SaaS.", cat: "Fundamentals", diff: "Easy" },
    { q: "How do you design a highly available architecture on AWS?", cat: "Architecture", diff: "Hard" },
    { q: "What is a VPC and how do you set up network segmentation in the cloud?", cat: "Networking", diff: "Medium" },
    { q: "Explain auto-scaling and how to configure it effectively.", cat: "Scalability", diff: "Medium" },
    { q: "What is serverless computing? Explain AWS Lambda and its limitations.", cat: "Serverless", diff: "Medium" },
    { q: "How do you implement disaster recovery in a cloud environment?", cat: "Reliability", diff: "Hard" },
    { q: "Explain cloud cost optimization strategies.", cat: "Cost Management", diff: "Medium" },
    { q: "What is a multi-cloud strategy and what are its challenges?", cat: "Strategy", diff: "Hard" },
    { q: "How do you secure cloud storage (S3, Blob Storage)?", cat: "Security", diff: "Medium" },
    { q: "Explain the concept of cloud-native architecture.", cat: "Architecture", diff: "Medium" },
    { q: "What are reserved instances vs spot instances and when to use each?", cat: "Cost Management", diff: "Easy" },
    { q: "How do you implement CI/CD pipelines in the cloud?", cat: "DevOps", diff: "Medium" },
    { q: "Explain cloud networking concepts: subnets, route tables, NAT gateways.", cat: "Networking", diff: "Medium" },
    { q: "What is a CDN and how do you configure one for a global application?", cat: "Performance", diff: "Easy" },
  ],
  sre: [
    { q: "What are SLOs, SLIs, and SLAs? How do you define them for a service?", cat: "Reliability", diff: "Medium" },
    { q: "Explain the concept of error budgets and how they guide engineering decisions.", cat: "Reliability", diff: "Hard" },
    { q: "How do you design a system for 99.99% availability?", cat: "Architecture", diff: "Hard" },
    { q: "What is a postmortem and what makes a good one?", cat: "Incident Management", diff: "Easy" },
    { q: "Explain the on-call process and how to manage alert fatigue.", cat: "Operations", diff: "Medium" },
    { q: "What is chaos engineering and how do you run Game Days?", cat: "Reliability", diff: "Hard" },
    { q: "How do you implement distributed tracing for microservices?", cat: "Observability", diff: "Medium" },
    { q: "Explain the difference between reactive and proactive reliability work.", cat: "Strategy", diff: "Medium" },
    { q: "What are the key metrics to monitor for a web service?", cat: "Monitoring", diff: "Easy" },
    { q: "How do you approach capacity planning for a growing service?", cat: "Operations", diff: "Hard" },
    { q: "Explain the toil concept from the Google SRE book.", cat: "Strategy", diff: "Medium" },
    { q: "How do you build runbooks that are actually useful during incidents?", cat: "Incident Management", diff: "Medium" },
    { q: "What is progressive delivery and how does it reduce deployment risk?", cat: "Deployment", diff: "Hard" },
    { q: "How do you ensure database reliability and backup strategies?", cat: "Operations", diff: "Medium" },
    { q: "Explain the four golden signals of monitoring.", cat: "Monitoring", diff: "Easy" },
  ],
  sysadmin: [
    { q: "Explain the difference between physical, virtual, and cloud servers.", cat: "Infrastructure", diff: "Easy" },
    { q: "How do you automate server provisioning and configuration management?", cat: "Automation", diff: "Medium" },
    { q: "What is RAID and which RAID level would you use for a database server?", cat: "Storage", diff: "Medium" },
    { q: "How do you implement a backup strategy for critical systems?", cat: "Backup & Recovery", diff: "Medium" },
    { q: "Explain how you would harden a Linux server for production use.", cat: "Security", diff: "Medium" },
    { q: "What is LDAP/Active Directory and how do you manage user access?", cat: "Identity Management", diff: "Medium" },
    { q: "How do you troubleshoot high CPU or memory usage on a server?", cat: "Troubleshooting", diff: "Easy" },
    { q: "Explain how to set up log management and centralized logging.", cat: "Monitoring", diff: "Medium" },
    { q: "What is a cron job and how do you schedule automated tasks?", cat: "Automation", diff: "Easy" },
    { q: "How do you manage SSL certificates at scale?", cat: "Security", diff: "Medium" },
    { q: "Explain filesystem types (ext4, XFS, ZFS) and when to use each.", cat: "Storage", diff: "Hard" },
    { q: "How do you implement high availability for a web server cluster?", cat: "Infrastructure", diff: "Hard" },
    { q: "What is DNS and how do you troubleshoot DNS resolution issues?", cat: "Networking", diff: "Easy" },
    { q: "How do you patch servers with minimal downtime?", cat: "Operations", diff: "Medium" },
    { q: "Explain the differences between systemd and init systems.", cat: "Linux", diff: "Medium" },
  ],
  network_architect: [
    { q: "Explain the OSI model and the role of each layer.", cat: "Fundamentals", diff: "Easy" },
    { q: "What is BGP and how does it enable internet routing?", cat: "Routing", diff: "Hard" },
    { q: "Explain the difference between TCP and UDP and when to use each.", cat: "Protocols", diff: "Easy" },
    { q: "How do you design a resilient network architecture for an enterprise?", cat: "Design", diff: "Hard" },
    { q: "What is SD-WAN and what problems does it solve?", cat: "WAN", diff: "Medium" },
    { q: "Explain VLAN, trunking, and inter-VLAN routing.", cat: "LAN", diff: "Medium" },
    { q: "What is a zero-trust network architecture?", cat: "Security", diff: "Hard" },
    { q: "How do you design network segmentation to limit blast radius?", cat: "Security", diff: "Hard" },
    { q: "Explain IPv6 and the challenges of migrating from IPv4.", cat: "Protocols", diff: "Medium" },
    { q: "What is MPLS and how does it improve WAN performance?", cat: "WAN", diff: "Hard" },
    { q: "How do you approach network capacity planning?", cat: "Operations", diff: "Medium" },
    { q: "Explain the role of a load balancer in network architecture.", cat: "Design", diff: "Easy" },
    { q: "What is QoS (Quality of Service) and how do you implement it?", cat: "Performance", diff: "Medium" },
    { q: "How do you secure wireless networks in an enterprise environment?", cat: "Security", diff: "Medium" },
    { q: "Explain the concept of network observability and how you achieve it.", cat: "Operations", diff: "Medium" },
  ],
  security_analyst: [
    { q: "What is a SIEM and how do you use it for threat detection?", cat: "Tools", diff: "Medium" },
    { q: "Explain the Cyber Kill Chain and how it guides incident response.", cat: "Frameworks", diff: "Medium" },
    { q: "How do you perform threat hunting proactively?", cat: "Threat Hunting", diff: "Hard" },
    { q: "What is the MITRE ATT&CK framework?", cat: "Frameworks", diff: "Medium" },
    { q: "How do you respond to a ransomware incident?", cat: "Incident Response", diff: "Hard" },
    { q: "Explain indicators of compromise (IoCs) and indicators of attack (IoAs).", cat: "Threat Intelligence", diff: "Medium" },
    { q: "What is vulnerability management and how do you prioritize patching?", cat: "Vulnerability Management", diff: "Medium" },
    { q: "How do you analyze network logs to detect suspicious activity?", cat: "Analysis", diff: "Medium" },
    { q: "Explain what a SOC (Security Operations Center) does.", cat: "Operations", diff: "Easy" },
    { q: "What are the steps of an incident response plan?", cat: "Incident Response", diff: "Medium" },
    { q: "How do you detect lateral movement in a network?", cat: "Threat Hunting", diff: "Hard" },
    { q: "Explain phishing attacks and how to detect them technically.", cat: "Threats", diff: "Easy" },
    { q: "What is threat intelligence and how do you operationalize it?", cat: "Threat Intelligence", diff: "Hard" },
    { q: "How do you perform a risk assessment for an organization?", cat: "Risk Management", diff: "Medium" },
    { q: "What is a false positive and how do you reduce alert fatigue in a SOC?", cat: "Operations", diff: "Medium" },
  ],
  pen_tester: [
    { q: "Walk me through a complete penetration testing methodology.", cat: "Methodology", diff: "Medium" },
    { q: "Explain the difference between black-box, grey-box, and white-box testing.", cat: "Methodology", diff: "Easy" },
    { q: "How do you perform reconnaissance without being detected?", cat: "Reconnaissance", diff: "Hard" },
    { q: "What is privilege escalation and how do you test for it on Linux?", cat: "Exploitation", diff: "Hard" },
    { q: "Explain how SQL injection can be used to bypass authentication.", cat: "Web Vulnerabilities", diff: "Medium" },
    { q: "What tools do you use for network scanning and why?", cat: "Tools", diff: "Easy" },
    { q: "How do you test for broken access control vulnerabilities?", cat: "Web Vulnerabilities", diff: "Medium" },
    { q: "What is a buffer overflow attack and how does it work?", cat: "Exploitation", diff: "Hard" },
    { q: "How do you write a professional penetration testing report?", cat: "Reporting", diff: "Medium" },
    { q: "Explain how to test wireless networks for security vulnerabilities.", cat: "Network Pentesting", diff: "Medium" },
    { q: "What is social engineering and how do you test an organization's resilience?", cat: "Social Engineering", diff: "Medium" },
    { q: "How do you test API security?", cat: "API Testing", diff: "Medium" },
    { q: "Explain the concept of a red team vs a blue team exercise.", cat: "Methodology", diff: "Easy" },
    { q: "What is CVE and how do you use the NVD for vulnerability research?", cat: "Vulnerability Research", diff: "Easy" },
    { q: "How do you test for insecure deserialization vulnerabilities?", cat: "Web Vulnerabilities", diff: "Hard" },
  ],
  security_architect: [
    { q: "How do you design a security architecture for a cloud-native application?", cat: "Architecture", diff: "Hard" },
    { q: "Explain the principle of defense in depth with a practical example.", cat: "Principles", diff: "Medium" },
    { q: "What is a zero-trust architecture and how do you implement it?", cat: "Architecture", diff: "Hard" },
    { q: "How do you perform threat modeling? Explain STRIDE.", cat: "Threat Modeling", diff: "Medium" },
    { q: "What are the key security considerations when designing APIs?", cat: "API Security", diff: "Medium" },
    { q: "How do you architect identity and access management (IAM) at enterprise scale?", cat: "IAM", diff: "Hard" },
    { q: "Explain the shared responsibility model in cloud security.", cat: "Cloud Security", diff: "Easy" },
    { q: "How do you ensure secrets management in a microservices environment?", cat: "Secrets Management", diff: "Medium" },
    { q: "What is PKI (Public Key Infrastructure) and when do you need it?", cat: "Cryptography", diff: "Hard" },
    { q: "How do you design for privacy by design principles?", cat: "Privacy", diff: "Medium" },
    { q: "What is a security architecture review process and how do you run one?", cat: "Process", diff: "Medium" },
    { q: "Explain how to harden container and Kubernetes environments.", cat: "Cloud Security", diff: "Hard" },
    { q: "What is federated identity and how does SAML/OIDC work?", cat: "IAM", diff: "Hard" },
    { q: "How do you approach secure software development lifecycle (SSDLC)?", cat: "Process", diff: "Medium" },
    { q: "What security controls would you implement for a fintech application?", cat: "Industry", diff: "Hard" },
  ],
  infosec_manager: [
    { q: "How do you build and manage a security team from scratch?", cat: "Leadership", diff: "Medium" },
    { q: "Explain how to create a comprehensive information security policy.", cat: "Policy", diff: "Medium" },
    { q: "How do you measure the ROI of security investments to executives?", cat: "Business", diff: "Hard" },
    { q: "What is ISO 27001 and how do you prepare an organization for certification?", cat: "Compliance", diff: "Medium" },
    { q: "How do you build a security awareness training program?", cat: "Training", diff: "Easy" },
    { q: "Explain the role of a CISO and how security strategy aligns with business goals.", cat: "Leadership", diff: "Hard" },
    { q: "How do you manage third-party vendor security risk?", cat: "Risk Management", diff: "Medium" },
    { q: "What is GDPR and what are the key compliance requirements for security?", cat: "Compliance", diff: "Medium" },
    { q: "How do you handle a major data breach from a management perspective?", cat: "Crisis Management", diff: "Hard" },
    { q: "Explain how to create and test a business continuity plan.", cat: "BCP", diff: "Medium" },
    { q: "How do you prioritize security investments when budget is limited?", cat: "Strategy", diff: "Hard" },
    { q: "What metrics do you track to measure security program effectiveness?", cat: "Metrics", diff: "Medium" },
    { q: "How do you balance security requirements with development velocity?", cat: "Strategy", diff: "Hard" },
    { q: "Explain the process of conducting a security risk assessment.", cat: "Risk Management", diff: "Medium" },
    { q: "How do you work with legal and compliance teams on security matters?", cat: "Business", diff: "Medium" },
  ],
  digital_forensics: [
    { q: "Explain the chain of custody and why it's critical in digital forensics.", cat: "Fundamentals", diff: "Easy" },
    { q: "How do you acquire a forensic image of a hard drive without altering it?", cat: "Evidence Collection", diff: "Medium" },
    { q: "What tools do you use for disk forensics and what do they reveal?", cat: "Tools", diff: "Medium" },
    { q: "Explain how to analyze Windows registry artifacts for evidence.", cat: "Windows Forensics", diff: "Hard" },
    { q: "What is memory forensics and what artifacts can you find in RAM?", cat: "Memory Forensics", diff: "Hard" },
    { q: "How do you investigate a potential insider threat?", cat: "Investigation", diff: "Hard" },
    { q: "Explain network forensics and how to reconstruct events from pcap files.", cat: "Network Forensics", diff: "Hard" },
    { q: "What is file carving and when do you need to use it?", cat: "Evidence Recovery", diff: "Medium" },
    { q: "How do you analyze mobile device artifacts during an investigation?", cat: "Mobile Forensics", diff: "Medium" },
    { q: "Explain the concept of anti-forensics and how attackers try to cover their tracks.", cat: "Advanced", diff: "Hard" },
    { q: "How do you write a digital forensics report that holds up in court?", cat: "Reporting", diff: "Medium" },
    { q: "What are prefetch files and what can they tell you in an investigation?", cat: "Windows Forensics", diff: "Medium" },
    { q: "How do you investigate a ransomware attack forensically?", cat: "Incident Response", diff: "Hard" },
    { q: "Explain how to analyze log files across multiple systems for a timeline.", cat: "Analysis", diff: "Medium" },
    { q: "What is e-discovery and how does it relate to digital forensics?", cat: "Legal", diff: "Easy" },
  ],
  blockchain_dev: [
    { q: "Explain how a blockchain achieves consensus without a central authority.", cat: "Fundamentals", diff: "Medium" },
    { q: "What is the difference between Proof of Work and Proof of Stake?", cat: "Consensus", diff: "Medium" },
    { q: "How do smart contracts work on Ethereum?", cat: "Smart Contracts", diff: "Medium" },
    { q: "What is a 51% attack and how does it threaten blockchain security?", cat: "Security", diff: "Medium" },
    { q: "Explain the ERC-20 and ERC-721 token standards.", cat: "Tokens", diff: "Easy" },
    { q: "How do you write secure Solidity code? Common vulnerabilities to avoid?", cat: "Smart Contracts", diff: "Hard" },
    { q: "What is a reentrancy attack and how do you prevent it?", cat: "Security", diff: "Hard" },
    { q: "Explain Layer 2 scaling solutions like Optimism and Arbitrum.", cat: "Scaling", diff: "Hard" },
    { q: "What is DeFi and what are the main protocol categories?", cat: "Applications", diff: "Medium" },
    { q: "How do you test and audit a smart contract before deployment?", cat: "Testing", diff: "Hard" },
    { q: "Explain the concept of gas in Ethereum and how to optimize for it.", cat: "Performance", diff: "Medium" },
    { q: "What is IPFS and how is it used in decentralized applications?", cat: "Infrastructure", diff: "Medium" },
    { q: "Explain the Oracle Problem in blockchain and how Chainlink solves it.", cat: "Advanced", diff: "Hard" },
    { q: "What are the use cases for private vs public blockchains?", cat: "Architecture", diff: "Easy" },
    { q: "How does a cross-chain bridge work and what are the risks?", cat: "Interoperability", diff: "Hard" },
  ],
  game_dev: [
    { q: "Explain the game loop and how it drives real-time game execution.", cat: "Fundamentals", diff: "Easy" },
    { q: "What is the difference between Unity and Unreal Engine? When would you choose each?", cat: "Engines", diff: "Easy" },
    { q: "How does physics simulation work in game engines?", cat: "Physics", diff: "Medium" },
    { q: "Explain the Entity-Component-System (ECS) architecture pattern.", cat: "Architecture", diff: "Medium" },
    { q: "How do you optimize a game to maintain 60 FPS on target hardware?", cat: "Performance", diff: "Hard" },
    { q: "What is draw call batching and how does it improve rendering performance?", cat: "Graphics", diff: "Hard" },
    { q: "Explain how multiplayer networking works in games (client-server vs P2P).", cat: "Networking", diff: "Hard" },
    { q: "What is lag compensation and how do you implement it?", cat: "Networking", diff: "Hard" },
    { q: "How do you design scalable game AI with behavior trees?", cat: "AI", diff: "Medium" },
    { q: "What is procedural content generation and how do you use it?", cat: "Game Design", diff: "Medium" },
    { q: "Explain the difference between forward and deferred rendering.", cat: "Graphics", diff: "Hard" },
    { q: "How do you implement a save/load system effectively?", cat: "Systems", diff: "Medium" },
    { q: "What is game balancing and how do you approach it?", cat: "Game Design", diff: "Easy" },
    { q: "Explain how shader programming works at a high level.", cat: "Graphics", diff: "Hard" },
    { q: "How do you profile and debug a game that has performance issues?", cat: "Performance", diff: "Medium" },
  ],
  embedded_engineer: [
    { q: "Explain the difference between a microcontroller and a microprocessor.", cat: "Fundamentals", diff: "Easy" },
    { q: "What is a real-time operating system (RTOS) and when do you need one?", cat: "RTOS", diff: "Medium" },
    { q: "How do you handle memory constraints in embedded systems?", cat: "Memory Management", diff: "Medium" },
    { q: "Explain I2C, SPI, and UART communication protocols.", cat: "Protocols", diff: "Medium" },
    { q: "What is interrupt-driven programming and how does it work?", cat: "Programming", diff: "Medium" },
    { q: "How do you debug an embedded system without a traditional debugger?", cat: "Debugging", diff: "Hard" },
    { q: "Explain the concept of a watchdog timer and why it's important.", cat: "Reliability", diff: "Easy" },
    { q: "What is DMA (Direct Memory Access) and when would you use it?", cat: "Hardware", diff: "Hard" },
    { q: "How do you write firmware that is both efficient and maintainable?", cat: "Programming", diff: "Medium" },
    { q: "Explain power management strategies for battery-powered devices.", cat: "Power", diff: "Hard" },
    { q: "What is a bootloader and how does it enable firmware updates?", cat: "Firmware", diff: "Medium" },
    { q: "How do you test embedded systems software?", cat: "Testing", diff: "Medium" },
    { q: "Explain the difference between hard real-time and soft real-time systems.", cat: "RTOS", diff: "Medium" },
    { q: "What is bit manipulation and when is it critical in embedded programming?", cat: "Programming", diff: "Medium" },
    { q: "How do you approach safety-critical embedded system design?", cat: "Safety", diff: "Hard" },
  ],
  iot_engineer: [
    { q: "Explain the typical architecture of an IoT system (device to cloud).", cat: "Architecture", diff: "Easy" },
    { q: "Compare MQTT, CoAP, and HTTP for IoT communication.", cat: "Protocols", diff: "Medium" },
    { q: "How do you secure IoT devices that have limited computing resources?", cat: "Security", diff: "Hard" },
    { q: "What is edge computing and why is it important for IoT?", cat: "Architecture", diff: "Medium" },
    { q: "Explain how device provisioning and onboarding works at scale.", cat: "Device Management", diff: "Medium" },
    { q: "How do you perform over-the-air (OTA) firmware updates securely?", cat: "Device Management", diff: "Hard" },
    { q: "What are the challenges of managing thousands of IoT devices?", cat: "Scale", diff: "Hard" },
    { q: "Explain time-series databases and why they're suited for IoT data.", cat: "Data", diff: "Medium" },
    { q: "How do you handle intermittent connectivity in IoT systems?", cat: "Reliability", diff: "Medium" },
    { q: "What is a digital twin and how is it used in IoT?", cat: "Advanced", diff: "Hard" },
    { q: "Explain the role of message brokers in IoT architectures.", cat: "Architecture", diff: "Medium" },
    { q: "How do you debug an IoT device that is deployed in the field?", cat: "Debugging", diff: "Hard" },
    { q: "What are the power consumption challenges in battery-operated IoT devices?", cat: "Hardware", diff: "Medium" },
    { q: "Explain how sensor fusion works in IoT applications.", cat: "Data Processing", diff: "Hard" },
    { q: "What are the privacy implications of IoT data collection?", cat: "Ethics", diff: "Medium" },
  ],
  ui_ux_designer: [
    { q: "Explain your design process from research to final delivery.", cat: "Process", diff: "Easy" },
    { q: "What is the difference between UX and UI design?", cat: "Fundamentals", diff: "Easy" },
    { q: "How do you conduct user research and incorporate findings into design?", cat: "Research", diff: "Medium" },
    { q: "Explain design thinking methodology and how you apply it.", cat: "Methodology", diff: "Medium" },
    { q: "How do you design for accessibility (WCAG guidelines)?", cat: "Accessibility", diff: "Medium" },
    { q: "What are the principles of good information architecture?", cat: "IA", diff: "Medium" },
    { q: "How do you create and maintain a design system?", cat: "Design Systems", diff: "Hard" },
    { q: "Explain how you handle design handoff to developers.", cat: "Collaboration", diff: "Easy" },
    { q: "What prototyping tools do you use and why?", cat: "Tools", diff: "Easy" },
    { q: "How do you approach designing for responsive and mobile-first experiences?", cat: "Responsive Design", diff: "Medium" },
    { q: "Explain usability testing methods and when to use each.", cat: "Research", diff: "Medium" },
    { q: "What is atomic design and how does it structure component-based design?", cat: "Design Systems", diff: "Medium" },
    { q: "How do you design for dark mode and theming?", cat: "Visual Design", diff: "Medium" },
    { q: "What metrics do you use to measure the success of a UX design?", cat: "Metrics", diff: "Hard" },
    { q: "How do you collaborate with product managers to translate requirements into design?", cat: "Collaboration", diff: "Medium" },
  ],
  ar_vr_dev: [
    { q: "Explain the difference between AR, VR, and MR (Mixed Reality).", cat: "Fundamentals", diff: "Easy" },
    { q: "What are the main platforms for AR/VR development today?", cat: "Platforms", diff: "Easy" },
    { q: "How do you optimize 3D rendering for VR to maintain comfortable frame rates?", cat: "Performance", diff: "Hard" },
    { q: "What is motion sickness in VR and how do you design to minimize it?", cat: "UX", diff: "Medium" },
    { q: "Explain how 6DOF (six degrees of freedom) tracking works.", cat: "Tracking", diff: "Medium" },
    { q: "What is spatial audio and why is it important for immersive experiences?", cat: "Audio", diff: "Medium" },
    { q: "How do you handle UI/UX design in a 3D spatial environment?", cat: "UX", diff: "Hard" },
    { q: "Explain how SLAM (Simultaneous Localization and Mapping) enables AR.", cat: "Tracking", diff: "Hard" },
    { q: "What is the role of WebXR and how does it enable browser-based AR/VR?", cat: "Web XR", diff: "Medium" },
    { q: "How do you test and validate AR/VR applications?", cat: "Testing", diff: "Medium" },
    { q: "Explain level of detail (LOD) and occlusion culling for VR performance.", cat: "Performance", diff: "Hard" },
    { q: "What are the challenges of multiplayer in VR environments?", cat: "Networking", diff: "Hard" },
    { q: "How would you design an onboarding experience for first-time VR users?", cat: "UX", diff: "Medium" },
    { q: "What is hand tracking and what are its limitations compared to controllers?", cat: "Input", diff: "Medium" },
    { q: "How do you approach accessibility in VR experiences?", cat: "Accessibility", diff: "Hard" },
  ],
  dba: [
    { q: "Explain the difference between clustered and non-clustered indexes.", cat: "Indexing", diff: "Medium" },
    { q: "What is query optimization? How do you read and interpret an execution plan?", cat: "Performance", diff: "Hard" },
    { q: "Explain database normalization (1NF, 2NF, 3NF, BCNF) with examples.", cat: "Design", diff: "Medium" },
    { q: "What is ACID compliance and why is it important?", cat: "Transactions", diff: "Easy" },
    { q: "How do you design a high-availability database cluster?", cat: "Architecture", diff: "Hard" },
    { q: "Explain replication strategies (synchronous vs asynchronous) and their trade-offs.", cat: "Replication", diff: "Hard" },
    { q: "How do you perform a database migration with zero downtime?", cat: "Operations", diff: "Hard" },
    { q: "What is database sharding and when should you implement it?", cat: "Scaling", diff: "Hard" },
    { q: "How do you implement a backup and recovery strategy for a critical database?", cat: "Backup", diff: "Medium" },
    { q: "Explain connection pooling and how to configure it optimally.", cat: "Performance", diff: "Medium" },
    { q: "What is a deadlock and how do you detect and prevent it?", cat: "Transactions", diff: "Medium" },
    { q: "How do you monitor database performance and identify bottlenecks?", cat: "Monitoring", diff: "Medium" },
    { q: "Explain partitioning strategies and their performance implications.", cat: "Performance", diff: "Hard" },
    { q: "What is database security hardening and what steps do you take?", cat: "Security", diff: "Medium" },
    { q: "How do you manage schema changes in a production database?", cat: "Operations", diff: "Medium" },
  ],
};

export function shuffleQuestions(questions, count = 5) {
  const shuffled = [...questions].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
